FUNCTION(LOAD_ARCH ARCH)
	FILE(GLOB ARCH_SRCS "arch/${ARCH}/*.S" "arch/${ARCH}/*.c")

	INCLUDE("arch/${ARCH}/flags.cmake")

	INCLUDE_DIRECTORIES(arch/${ARCH}/include)

	SET(ARCH_SRCS ${ARCH_SRCS} PARENT_SCOPE)
	SET(ARCH_LAYOUT "${CMAKE_SOURCE_DIR}/src/kernel/arch/${ARCH}/layout.ld" PARENT_SCOPE)

	SET(ARCH_C_FLAGS ${ARCH_C_FLAGS} PARENT_SCOPE)
	SET(ARCH_ASM_FLAGS ${ARCH_ASM_FLAGS} PARENT_SCOPE)
ENDFUNCTION(LOAD_ARCH)